controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: 'App\Controller\HomeController::index'


user_register:
    path: /register
    controller: App\Controller\CompteController::register

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout